abdulrasool/urls.py
from django.contrib import admin
from django.views.static import serve
from django.urls import include, path, re_path
from abdulrasool import settings
from main import views as general_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app/accounts/', include('registration.backends.default.urls')),
    path('super-admin/',include(('main.urls'),namespace='main')),
    path('super-admin/',general_views.app,name='app'),
    
    # admin panel
    path('super-admin/product/',include(('product.urls'),namespace='product')),
    path('super-admin/web/',include(('web.urls'),namespace='web')),
    
    # web
    path('', include('web.urls', namespace="web")),    
    
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT})
]

product/urls.py
from . import views
from django.urls import path, re_path

# Create your tests here.

app_name = 'product'

urlpatterns = [
    path('category/', views.category_view, name='category'),
    re_path(r'^category-view/(?P<pk>.*)/$', views.category_single_view, name='category_single'),
    re_path(r'^create-category/$', views.create_category_view, name='create_category'),
    re_path(r'^edit-category/(?P<pk>.*)/$', views.edit_category_view, name='edit_category'),
    re_path(r'^delete-category/(?P<pk>.*)/$', views.delete_category_view, name='delete_category'),


    path('product/', views.product_view, name='product'),
    re_path(r'^product-view/(?P<pk>.*)/$', views.product_single_view, name='product_single'),
    re_path(r'^create-product/$', views.create_product_view, name='create_product'),
    re_path(r'^edit-product/(?P<pk>.*)/$', views.edit_product_view, name='edit_product'),
    re_path(r'^delete-product/(?P<pk>.*)/$', views.delete_product_view, name='delete_product'),
]

web/urls.py
from . import views
from django.urls import path, re_path

# Create your tests here.

app_name = 'web'

urlpatterns = [
    path('', views.index, name="index"),
    path('product-category', views.product_category_view, name="product_category"),
    
    path('service/', views.service_view, name='service'),
    re_path(r'^service-view/(?P<pk>.*)/$', views.service_single_view, name='service_single'),
    re_path(r'^create-service/$', views.create_service_view, name='create_service'),
    re_path(r'^edit-service/(?P<pk>.*)/$', views.edit_service_view, name='edit_service'),
    re_path(r'^delete-service/(?P<pk>.*)/$', views.delete_service_view, name='delete_service'),
    
    
    path('career/', views.career_view, name='career'),
    re_path(r'^career-view/(?P<pk>.*)/$', views.career_single_view, name='career_single'),
    re_path(r'^create-career/$', views.create_career_view, name='create_career'),
    re_path(r'^edit-career/(?P<pk>.*)/$', views.edit_career_view, name='edit_career'),
    re_path(r'^delete-career/(?P<pk>.*)/$', views.delete_career_view, name='delete_career'),
    
    
    path('team-member/', views.team_members_view, name='team_member'),
    re_path(r'^team-member-view/(?P<pk>.*)/$', views.team_members_single_view, name='team_single'),
    re_path(r'^create-team-member/$', views.create_team_member_view, name='create_team_member'),
    re_path(r'^edit-team-member/(?P<pk>.*)/$', views.edit_team_member_view, name='edit_team_member'),
    re_path(r'^delete-team-member/(?P<pk>.*)/$', views.delete_team_member_view, name='delete_team_member'),
    
    
    path('about-us/', views.about_us_view, name='about_us'),
    re_path(r'^about-us-view/(?P<pk>.*)/$', views.about_us_single_view, name='about_us_single'),
    re_path(r'^create-about-us/$', views.create_about_us_view, name='create_about_us'),
    re_path(r'^edit-about-us/(?P<pk>.*)/$', views.edit_about_us_view, name='edit_about_us'),
    re_path(r'^delete-about-us/(?P<pk>.*)/$', views.delete_about_us_view, name='delete_about_us'),


    path('testimonial/', views.testimonial_view, name='testimonial'),
    re_path(r'^testimonial-view/(?P<pk>.*)/$', views.testimonial_single_view, name='testimonial_single'),
    re_path(r'^create-testimonial/$', views.create_testimonial_view, name='create_testimonial'),
    re_path(r'^edit-testimonial/(?P<pk>.*)/$', views.edit_testimonial_view, name='edit_testimonial'),
    re_path(r'^delete-testimonial/(?P<pk>.*)/$', views.delete_testimonial_view, name='delete_testimonial'),
    
    
    path('address/', views.address_view, name='address'),
    re_path(r'^address-view/(?P<pk>.*)/$', views.address_single_view, name='address_single'),
    re_path(r'^create-address/$', views.create_address_view, name='create_address'),
    re_path(r'^edit-address/(?P<pk>.*)/$', views.edit_address_view, name='edit_address'),
    re_path(r'^delete-address/(?P<pk>.*)/$', views.delete_address_view, name='delete_address'),
    
    
    path('connect/', views.connect_view, name='connect'),
    re_path(r'^create-connect/$', views.create_connect_view, name='create_connect'),
    re_path(r'^edit-connect/(?P<pk>.*)/$', views.edit_connect_view, name='edit_connect'),
    re_path(r'^delete-connect/(?P<pk>.*)/$', views.delete_connect_view, name='delete_connect'),
    
    path('description/', views.description_view, name='description'),
    re_path(r'^create-description/$', views.create_description_view, name='create_description'),
    re_path(r'^edit-description/(?P<pk>.*)/$', views.edit_description_view, name='edit_description'),

]

product/models.py
from unicodedata import category
from django.db import models
from main.models import BaseModel
from versatileimagefield.fields import VersatileImageField

# Create your models here.

class Category(BaseModel):
    title = models.CharField(max_length=255)
    description_title = models.CharField(max_length=255)
    description = models.TextField()
    image = VersatileImageField('Image', upload_to="product/category")

    class Meta:
        db_table = 'product_category'
        verbose_name = ('Product Category')
        verbose_name_plural = ('Product Category')
        ordering = ('auto_id',)

    def __str__(self):
        return str(self.title)
    
    
class Product(BaseModel):
    category = models.ForeignKey(Category,on_delete=models.CASCADE,limit_choices_to={'is_deleted': False})
    name = models.CharField(max_length=255)
    color = models.CharField(max_length=255)
    image = VersatileImageField('Image', upload_to="product/product")

    class Meta:
        db_table = 'product_product'
        verbose_name = ('Product Product')
        verbose_name_plural = ('Product Product')
        ordering = ('auto_id',)

    def __str__(self):
        return str(self.name)

web/models.py
from django.db import models
from main.models import BaseModel
from versatileimagefield.fields import VersatileImageField
from main.variables import phone_regex

# Create your models here.

OFFICE_TYPE =(
    ("main_office","Main Office"),
    ("sub_office","Sub Office"),
)


class Service(BaseModel):
    title = models.CharField(max_length=255)
    description = models.TextField()
    image = VersatileImageField('Image', upload_to="web/service")

    class Meta:
        db_table = 'web_services'
        verbose_name = ('Services')
        verbose_name_plural = ('Services')
        ordering = ('auto_id',)

    def __str__(self):
        return str(self.title)
    

class Career(BaseModel):
    title = models.CharField(max_length=255)
    description = models.TextField()
    email = models.EmailField()

    class Meta:
        db_table = 'web_career'
        verbose_name = ('Career')
        verbose_name_plural = ('Career')
        ordering = ('auto_id',)

    def __str__(self):
        return str(self.title)
    

class TeamMember(BaseModel):
    name = models.CharField(max_length=255)
    designation = models.CharField(max_length=255)
    instagram_link = models.URLField()
    facebook_link = models.URLField()
    twitter_link = models.URLField()
    whatsapp_link = models.URLField()

    class Meta:
        db_table = 'web_team_member'
        verbose_name = ('Team Member')
        verbose_name_plural = ('Team Member')
        ordering = ('auto_id',)

    def __str__(self):
        return str(self.name)
    

class AboutUs(BaseModel):
    title = models.CharField(max_length=255)
    description = models.TextField()
    image = VersatileImageField('Image', upload_to="web/aboutus")

    class Meta:
        db_table = 'web_about_us'
        verbose_name = ('About Us')
        verbose_name_plural = ('About Us')
        ordering = ('auto_id',)

    def __str__(self):
        return str(self.title)
    

class Testimonial(BaseModel):
    name = models.CharField(max_length=255)
    description = models.TextField()
    image = VersatileImageField('Image', upload_to="web/testimonial")
    rating = models.PositiveIntegerField()

    class Meta:
        db_table = 'web_testimonial'
        verbose_name = ('Testimonial')
        verbose_name_plural = ('Testimonial')
        ordering = ('auto_id',)

    def __str__(self):
        return str(self.name)
    
    
class Address(BaseModel):
    phone = models.CharField(max_length=15 ,validators=[phone_regex],)
    email = models.EmailField()
    location = models.TextField()
    location_url = models.URLField()
    office_type = models.CharField(max_length=200,choices=OFFICE_TYPE)

    class Meta:
        db_table = 'web_address'
        verbose_name = ('Address')
        verbose_name_plural = ('Address')
        ordering = ('auto_id',)

    def __str__(self):
        return str(self.phone)
    
    
class Connect(BaseModel):
    instagram_link = models.URLField()
    facebook_link = models.URLField()
    twitter_link = models.URLField()
    linkedin_link = models.URLField()

    class Meta:
        db_table = 'web_connect'
        verbose_name = ('Connect')
        verbose_name_plural = ('Connect')
        ordering = ('auto_id',)

    def __str__(self):
        return str(self.instagram_link)
    

class Description(BaseModel):
    we_provides = models.TextField()
    our_services = models.TextField()
    careers = models.TextField()
    team_members = models.TextField()
    about_us = models.TextField()

    class Meta:
        db_table = 'web_description'
        verbose_name = ('Description')
        verbose_name_plural = ('Description')
        ordering = ('auto_id',)

    def __str__(self):
        return str(self.id)
    
    

product/forms.py
from unicodedata import category
from django import forms
from django.forms.widgets import TextInput,Textarea,Select,DateInput,CheckboxInput,FileInput

from product.models import Category, Product


class CategoryForm(forms.ModelForm):
        
    class Meta:
        model = Category
        fields = ['title','description_title','description','image']
            
        widgets = {
            'title': TextInput(attrs={'class': 'required form-control h-20','placeholder' : 'Enter Title'}),
            'description_title': TextInput(attrs={'class': 'required form-control h-20','placeholder' : 'Enter Description Title'}),
            'description': Textarea(attrs={'class': 'required form-control text-area','placeholder' : 'Enter Description'}),
            'image': FileInput(attrs={'class': 'form-control dropify'}), 
        }
        
    def clean_image(self):
        
        image_file = self.cleaned_data.get('image')
        if not (image_file.name.endswith(".jpg") or image_file.name.endswith(".png")):
            raise forms.ValidationError("Only .jpg or .png files are accepted")
        return image_file
    
    
    
class ProductForm(forms.ModelForm):
        
    class Meta:
        model = Product
        fields = ['category','name','color','image']
            
        widgets = {
            'category': Select(attrs={'class': 'select2 form-control mb-3 custom-select','placeholder' : 'Select Category'}),
            'name': TextInput(attrs={'class': 'required form-control h-20','placeholder' : 'Enter Name'}),
            'color': TextInput(attrs={'class': 'required form-control h-20','placeholder' : 'Enter Color'}),
            'image': FileInput(attrs={'class': 'form-control dropify'}), 
        }
        
    def clean_image(self):
        
        image_file = self.cleaned_data.get('image')
        if not (image_file.name.endswith(".jpg") or image_file.name.endswith(".png")):
            raise forms.ValidationError("Only .jpg or .png files are accepted")
        return image_file

templates/admin_panel/product/about_us_list.html
{% extends 'admin_panel/base.html' %}
{% load static %}

{% block content %}
    <!-- Page Content-->
    <div class="page-content">

        <div class="container-fluid">
            <!-- Page-Title -->
            <div class="row">
                <div class="col-sm-12">
                    <div class="page-title-box">
                        <div class="row">
                            <div class="col">
                                <h4 class="page-title">{{page_title}}</h4>
   
                            </div><!--end col-->
                            <div class="col-auto align-self-center">
                                <a class="btn btn-outline-primary btn-icon-text"  href="{% url 'web:create_about_us' %}" > Create <i class="ti-plus btn-icon-append"></i></a>
                            </div><!--end col--> 

                        </div><!--end row-->                                                              
                    </div><!-- end page-title-box -->
                </div><!--end col-->
            </div><!--end row-->
            <!-- end page title end breadcrumb -->
            {% if instances %}
            <div class="row">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-header">
                            <h4 class="card-title">List view</h4>
                        </div>
                        <!--end card-header-->
                        <div class="card-body">
                            
                            <div class="table-responsive">
                                <table class="table mb-0">
                                    <thead>
                                        
                                        <tr>
                                            <th>SL.No</th>
                                            <th>Image</th>
                                            <th>Title</th>
                                            <th class="text-right">Action</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% for instance in instances %}
                                        <tr>
                                            <td>{{forloop.counter}}</td>
                                            <td>
                                                {% if instance.image %}
                                                <img src="{{instance.image.url}}" alt="" height="40" width="15%">
                                                {% endif %}
                                            </td>
                                            <td>{{instance.title}}</td>
                                                
                                            <td class="text-right">
                                                <a href="{% url 'web:about_us_single' pk=instance.pk %}"><i class="las la-eye text-info font-18"></i></a>
                                                <a href="{% url 'web:edit_about_us' pk=instance.pk %}"><i class="las la-pen text-info font-18"></i></a>
                                                <a class="action-button remove btn btn-default btn-icon" style="padding:0;"
                                                 data-id="{{instance.pk}}" data-text="{{confirm_delete_message}}" data-title="Are you sure?" href="{% url 'web:delete_about_us' pk=instance.pk %}"><i class="las la-trash-alt text-danger font-18"></i></a>
                                            </td>
                                        </tr>
                                        {% endfor %}
                               
                                    </tbody>
                                </table>
                                <!--end /table-->
                            </div>
                            <!--end /tableresponsive-->
                            <!-- pagination -->
                            
                        </div>
                        <!--end card-body-->
                    </div>
                    <!--end card-->
                </div> <!-- end col -->
            </div>
            {% else %}
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-body">  
                        <div class="text-center">
                            <img class="mb-3 rounded-circle" width="500px;" src="{% static 'admin_panel/assets/images/nothing_found.jpg' %}" alt="" /> 
                            <br />                                     
                            <a  href="{% url 'web:create_about_us' %}" class="btn btn-outline-primary btn-icon-text">Create {{page_title}}</a>
                        </div>
                    </div><!--end card-body-->
                </div><!--end card-->
            </div><!--end col-->  
            {% endif %}
        </div><!-- container -->
    <!-- end page content -->
{% endblock content %}
        

templates/admin_panel/product/about_us_single.html
{% extends 'admin_panel/base.html' %}
{% load static %}

{% block content %}
    <!-- Page Content-->
    <div class="page-content">
        <div class="container-fluid">
            <!-- Page-Title -->
            <div class="row">
                <div class="col-sm-12">
                    <div class="page-title-box">
                        <div class="row">
                            <div class="col">
                                <h4 class="page-title">{{page_title}}</h4>
                                <ol class="breadcrumb">
                                    <li class="breadcrumb-item"><a href="javascript:void(0);">Dashboard</a></li>
                                    <li class="breadcrumb-item"><a href="javascript:void(0);">Products</a></li>
                                    <li class="breadcrumb-item active">{{active_page_name}}</li>
                                </ol>
                            </div><!--end col-->
                            <div class="col-auto align-self-center">
                                <a class="btn btn-success btn-sm text-white px-4 d-inline-block"  href="{% url 'web:create_about_us' %}" ><i class="mdi mdi-plus mr-2"></i>Add New</a>
                                <a href="{% url 'web:edit_about_us' pk=instance.pk %}" class="btn btn-primary btn-sm text-white px-4 d-inline-block" style="background: #12a4ed !important;border-color: #12a4ed !important;"><i class="mdi mdi-pen mr-2"></i>Edit</a>
                                <a data-id="{{ instance.pk }}" class="action-button remove redirect btn btn-primary btn-sm text-white px-4 d-inline-block"  href="{% url 'web:delete_about_us' pk=instance.pk %}" data-text="{{ confirm_delete_message }}" data-title="Are you sure?" style="background: #f5325c !important;border-color: #f5325c !important;"><i class="mdi mdi-trash-can-outline mr-2"></i>Delete</a>
                            </div><!--end col--> 
                        </div><!--end row-->                                                              
                    </div><!--end page-title-box-->
                </div><!--end col-->
            </div><!--end row-->
            <!-- end page title end breadcrumb -->

            <!--product details row-->
            <div class="row">
                <div class="col-6">
                    

                    <div class="card">
                        <div class="card-header">
                            <h4 class="card-title">{{instance.title}}</h4>
                        </div><!--end card-header-->
                        <div class="card-body">
                            <p>Description : </p>
                            <p class="card-text text-muted">
                                {{instance.description}}
                            </p>
                            {% if instance.image %}
                            <img src="{{instance.image.url}}">
                            {% endif %}
                        </div><!--end card -body-->
                    </div><!--end card--> 
                    
                </div> <!-- end col -->
            </div> <!-- end row -->

        </div><!-- container -->
    </div>
    <!-- end page content -->
{% endblock content %}
        

templates/admin_panel/product/address_list.html
{% extends 'admin_panel/base.html' %}
{% load static %}

{% block content %}
    <!-- Page Content-->
    <div class="page-content">

        <div class="container-fluid">
            <!-- Page-Title -->
            <div class="row">
                <div class="col-sm-12">
                    <div class="page-title-box">
                        <div class="row">
                            <div class="col">
                                <h4 class="page-title">{{page_title}}</h4>
   
                            </div><!--end col-->
                            <div class="col-auto align-self-center">
                                <a class="btn btn-outline-primary btn-icon-text"  href="{% url 'web:create_address' %}" > Create <i class="ti-plus btn-icon-append"></i></a>
                            </div><!--end col--> 
                            
                        </div><!--end row-->                                                              
                    </div><!-- end page-title-box -->
                </div><!--end col-->
            </div><!--end row-->
            <!-- end page title end breadcrumb -->
            {% if instances %}
            <div class="row">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-header">
                            <h4 class="card-title">List view</h4>
                        </div>
                        <!--end card-header-->
                        <div class="card-body">
                            
                            <div class="table-responsive">
                                <table class="table mb-0">
                                    <thead>
                                        
                                        <tr>
                                            <th>SL.No</th>
                                            <th>Phone</th>
                                            <th>Email</th>
                                            <th>Location</th>
                                            <th>Location Url</th>
                                            <th>Office Type</th>
                                            <th class="text-right">Action</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% for instance in instances %}
                                        <tr>
                                            <td>{{forloop.counter}}</td>
                                            <td>{{instance.phone}}</td>
                                            <td>{{instance.email}}</td>
                                            <td>{{instance.location}}</td>
                                            <td><a href="{{instance.location_url}}">{{instance.location_url}}</a></td>
                                            <td>{{instance.get_office_type_display}}</td>
                                                
                                            <td class="text-right">
                                                {% comment %} <a href="{% url 'product:category_single' pk=instance.pk %}"><i class="las la-eye text-info font-18"></i></a> {% endcomment %}
                                                <a href="{% url 'web:edit_address' pk=instance.pk %}"><i class="las la-pen text-info font-18"></i></a>
                                                <a class="action-button remove btn btn-default btn-icon" style="padding:0;"
                                                 data-id="{{instance.pk}}" data-text="{{confirm_delete_message}}" data-title="Are you sure?" href="{% url 'web:delete_address' pk=instance.pk %}"><i class="las la-trash-alt text-danger font-18"></i></a>
                                            </td>
                                        </tr>
                                        {% endfor %}
                               
                                    </tbody>
                                </table>
                                <!--end /table-->
                            </div>
                            <!--end /tableresponsive-->
                            <!-- pagination -->
                            
                        </div>
                        <!--end card-body-->
                    </div>
                    <!--end card-->
                </div> <!-- end col -->
            </div>
            {% else %}
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-body">  
                        <div class="text-center">
                            <img class="mb-3 rounded-circle" width="500px;" src="{% static 'admin_panel/assets/images/nothing_found.jpg' %}" alt="" /> 
                            <br />                                     
                            <a  href="{% url 'web:create_address' %}" class="btn btn-outline-primary btn-icon-text">Create {{page_title}}</a>
                        </div>
                    </div><!--end card-body-->
                </div><!--end card-->
            </div><!--end col-->  
            {% endif %}
        </div><!-- container -->
    <!-- end page content -->
{% endblock content %}
        

templates/admin_panel/product/category.html
{% extends 'admin_panel/base.html' %}
{% load static %}

{% block content %}
    <!-- Page Content-->
    <div class="page-content">

        <div class="container-fluid">
            <!-- Page-Title -->
            <div class="row">
                <div class="col-sm-12">
                    <div class="page-title-box">
                        <div class="row">
                            <div class="col">
                                <h4 class="page-title">{{page_title}}</h4>
   
                            </div><!--end col-->
                            <div class="col-auto align-self-center">
                                <a class="btn btn-outline-primary btn-icon-text"  href="{% url 'product:create_category' %}" > Create <i class="ti-plus btn-icon-append"></i></a>
                            </div><!--end col--> 
                        </div><!--end row-->                                                              
                    </div><!-- end page-title-box -->
                </div><!--end col-->
            </div><!--end row-->
            <!-- end page title end breadcrumb -->
            {% if instances %}
            <div class="row">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-header">
                            <h4 class="card-title">List view</h4>
                        </div>
                        <!--end card-header-->
                        <div class="card-body">
                            
                            <div class="table-responsive">
                                <table class="table mb-0">
                                    <thead>
                                        
                                        <tr>
                                            <th>SL.No</th>
                                            <th>Image</th>
                                            <th>Title</th>
                                            <th class="text-right">Action</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% for instance in instances %}
                                        <tr>
                                            <td>{{forloop.counter}}</td>
                                            <td>
                                                {% if instance.image %}
                                                <img src="{{instance.image.url}}" alt="" height="40" width="15%">
                                                {% endif %}
                                            </td>
                                            <td>{{instance.title}}</td> 
                                                
                                            <td class="text-right">
                                                <a href="{% url 'product:category_single' pk=instance.pk %}"><i class="las la-eye text-info font-18"></i></a>
                                                <a href="{% url 'product:edit_category' pk=instance.pk %}"><i class="las la-pen text-info font-18"></i></a>
                                                <a class="action-button remove btn btn-default btn-icon" style="padding:0;"
                                                 data-id="{{instance.pk}}" data-text="{{confirm_delete_message}}" data-title="Are you sure?" href="{% url 'product:delete_category' pk=instance.pk %}"><i class="las la-trash-alt text-danger font-18"></i></a>
                                            </td>
                                        </tr>
                                        {% endfor %}
                               
                                    </tbody>
                                </table>
                                <!--end /table-->
                            </div>
                            <!--end /tableresponsive-->
                            <!-- pagination -->
                            
                        </div>
                        <!--end card-body-->
                    </div>
                    <!--end card-->
                </div> <!-- end col -->
            </div>
            {% else %}
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-body">  
                        <div class="text-center">
                            <img class="mb-3 rounded-circle" width="500px;" src="{% static 'admin_panel/assets/images/nothing_found.jpg' %}" alt="" /> 
                            <br />                                     
                            <a  href="{% url 'product:create_category' %}" class="btn btn-outline-primary btn-icon-text">Create {{page_title}}</a>
                        </div>
                    </div><!--end card-body-->
                </div><!--end card-->
            </div><!--end col-->  
            {% endif %}
        </div><!-- container -->
    <!-- end page content -->
{% endblock content %}
        