abdulrasool/urls.py
from django.contrib import admin
from django.views.static import serve
from django.urls import include, path, re_path
from abdulrasool import settings
from main import views as general_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app/accounts/', include('registration.backends.default.urls')),
    path('super-admin/',include(('main.urls'),namespace='main')),
    path('super-admin/',general_views.app,name='app'),
    
    # admin panel
    path('super-admin/product/',include(('product.urls'),namespace='product')),
    path('super-admin/web/',include(('web.urls'),namespace='web')),
    
    # web
    path('', include('web.urls', namespace="web")),    
    
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT})
]

web/urls.py
from . import views
from django.urls import path, re_path

# Create your tests here.

app_name = 'web'

urlpatterns = [
    path('', views.index, name="index"),
    path('product-category', views.product_category_view, name="product_category"),
    
    path('service/', views.service_view, name='service'),
    re_path(r'^service-view/(?P<pk>.*)/$', views.service_single_view, name='service_single'),
    re_path(r'^create-service/$', views.create_service_view, name='create_service'),
    re_path(r'^edit-service/(?P<pk>.*)/$', views.edit_service_view, name='edit_service'),
    re_path(r'^delete-service/(?P<pk>.*)/$', views.delete_service_view, name='delete_service'),
    
    
    path('career/', views.career_view, name='career'),
    re_path(r'^career-view/(?P<pk>.*)/$', views.career_single_view, name='career_single'),
    re_path(r'^create-career/$', views.create_career_view, name='create_career'),
    re_path(r'^edit-career/(?P<pk>.*)/$', views.edit_career_view, name='edit_career'),
    re_path(r'^delete-career/(?P<pk>.*)/$', views.delete_career_view, name='delete_career'),
    
    
    path('team-member/', views.team_members_view, name='team_member'),
    re_path(r'^team-member-view/(?P<pk>.*)/$', views.team_members_single_view, name='team_single'),
    re_path(r'^create-team-member/$', views.create_team_member_view, name='create_team_member'),
    re_path(r'^edit-team-member/(?P<pk>.*)/$', views.edit_team_member_view, name='edit_team_member'),
    re_path(r'^delete-team-member/(?P<pk>.*)/$', views.delete_team_member_view, name='delete_team_member'),
    
    
    path('about-us/', views.about_us_view, name='about_us'),
    re_path(r'^about-us-view/(?P<pk>.*)/$', views.about_us_single_view, name='about_us_single'),
    re_path(r'^create-about-us/$', views.create_about_us_view, name='create_about_us'),
    re_path(r'^edit-about-us/(?P<pk>.*)/$', views.edit_about_us_view, name='edit_about_us'),
    re_path(r'^delete-about-us/(?P<pk>.*)/$', views.delete_about_us_view, name='delete_about_us'),


    path('testimonial/', views.testimonial_view, name='testimonial'),
    re_path(r'^testimonial-view/(?P<pk>.*)/$', views.testimonial_single_view, name='testimonial_single'),
    re_path(r'^create-testimonial/$', views.create_testimonial_view, name='create_testimonial'),
    re_path(r'^edit-testimonial/(?P<pk>.*)/$', views.edit_testimonial_view, name='edit_testimonial'),
    re_path(r'^delete-testimonial/(?P<pk>.*)/$', views.delete_testimonial_view, name='delete_testimonial'),
    
    
    path('address/', views.address_view, name='address'),
    re_path(r'^address-view/(?P<pk>.*)/$', views.address_single_view, name='address_single'),
    re_path(r'^create-address/$', views.create_address_view, name='create_address'),
    re_path(r'^edit-address/(?P<pk>.*)/$', views.edit_address_view, name='edit_address'),
    re_path(r'^delete-address/(?P<pk>.*)/$', views.delete_address_view, name='delete_address'),
    
    
    path('connect/', views.connect_view, name='connect'),
    re_path(r'^create-connect/$', views.create_connect_view, name='create_connect'),
    re_path(r'^edit-connect/(?P<pk>.*)/$', views.edit_connect_view, name='edit_connect'),
    re_path(r'^delete-connect/(?P<pk>.*)/$', views.delete_connect_view, name='delete_connect'),
    
    path('description/', views.description_view, name='description'),
    re_path(r'^create-description/$', views.create_description_view, name='create_description'),
    re_path(r'^edit-description/(?P<pk>.*)/$', views.edit_description_view, name='edit_description'),

]

templates/web/index.html
{% extends 'web/web_base.html' %}
{% load static %}
{% load web_templates_tags %}
{% block content %}


<section id="provide">
    <div class="wrapper">
      <div class="head" id="category">
        <h4>We Provides</h4>
        <p>
            If you choose us to provide your quality workplace furniture, we offer a variety of customizable service levels ranging from drop-shipping to your location
        </p>
      </div>
      <!-- <ul class="category" id="tab-select"> -->
      <ul class="services-slider" id="tab-select">
        {% for category in categories %}
        <li id="li{{category.pk}}" class="{% if forloop.first %}first-category-li{% endif %}" data-url="{% url 'web:product_category' %}" onclick="product_ajax('{{category.pk}}')">
          <a style="color: #000;" href="javascript:void(0);">
            <span><img src="{{category.image.url}}" alt="Chair" /></span>
            <small>{{category.title}}</small>
          </a>
        </li>
        {% endfor %}
      </ul>
      <!-- category-section -->
    </div>
  </section>
  <!-- provide-end -->

  <section id="designs">
    <div class="wrapper">
      <!-- loop-items-for-categories -->
      <div class="box tab-box" id="tab01">
            <ul class="slider-item">

                <li>
                    <a href="#"
                    ><span
                        ><img src="" alt="Chair"
                    /></span>
                    <div class="info">
                        <h5></h5>
                        <p></p>
                    </div>
                    </a>
                </li>

            </ul>

            <div class="text-box">
                <h3 id="cat_description_title"></h3>
                <p id="cat_description_description">

                </p>
                <!-- <a href="" class="button">Read More</a> -->
            </div>
      </div>
    </div>
  </section>
  <!-- designsy -->
{%  if instances %}
<section id="services">
    <div class="wrapper">
        <div class="head">
        <h3>Our Services & Interiar Desings</h3>
        <p>
            {{descriptions.our_services}}
        </p>
        </div>
        <div class="container">
        <ul class="page-item">
            {% for service in instances %}
            <li class="pagination-item">
                <a href="#">
                    <div class="img-box">
                    <img
                        src="{{service.image.url}}"
                        alt="Office"
                        class="small-image"
                    />
                    <span>{{service.title}}</span>
                    </div>
                    <div class="info">
                    <h4>{{service.title}}</h4>
                    <p>
                        {{service.description}}
                    </p>
                    </div>
                </a>
            </li>
            {% endfor %}

        </ul>
        <div id="pagination-container"></div>
        </div>
    </div>
</section>
{% endif %}
<!-- services-end -->

  <!-- careers -->
<section id="careers">
    <div class="wrapper">
        <div class="head">
        <h2>Careers</h2>
        <p>
            {{descriptions.careers}}
        </p>
        </div>
        <div class="container">
        <ul>
            {% for career in careers %}
            <li>
                <h5>{{career.title}}</h5>
                <p>
                    {{career.description}}
                </p>
                <span>Mail us : {{career.email}}</span>
            </li>
            {% endfor %}
        </ul>
        </div>
    </div>
</section>

  <!-- members-section -->
<section id="members">
    <div class="wrapper">
        <div class="head">
        <h2>Our Team Members</h2>
        <p>
            {{descriptions.team_members}}
        </p>
        </div>
        <div class="container">
        <ul>
            {% for team in teams %}
            <li>
                <div class="avatar">
                    <img src="{% static 'web/images/users.png' %}" alt="User" />
                </div>
                <h4>{{team.name}}</h4>
                <small>{{team.designation}}</small>
                <div class="social">
                    <span
                    ><a target="_blank" href="{{team.instagram_link}}"
                        ><img src="{% static 'web/images/instagram.svg' %}" alt="Instagram" /></a
                    ></span>
                    <span
                    ><a target="_blank" href="{{team.facebook_link}}"><img src="{% static 'web/images/fb.svg' %}" alt="Facebook" /></a
                    ></span>
                    <span
                    ><a target="_blank" href="{{team.twitter_link}}"
                        ><img src="{% static 'web/images/twitter.svg' %}" alt="Twitter" /></a
                    ></span>
                    <span>
                        <a target="_blank" href="{{team.whatsapp_link}}">
                            <img class="wtsp" src="{% static 'web/images/whatsapp.svg' %}" alt="Whatsapp" />
                        </a>
                    </span>
                </div>
            </li>
            {% endfor %}

        </ul>
        </div>
    </div>
</section>


<!-- about-us -->
<section id="about">
    <div class="wrapper">
        <div class="head">
        <h2>Know About Us</h2>
        <p>
            {{descriptions.about_us}}
        </p>
        </div>
        <div class="container">
            {% for about in about_us %}
            {% if forloop.counter|divisibleby:2 %}
            <div class="items">
                <div class="text-box left">
                    <h4>{{about.title}}</h4>
                    <p>{{about.description}}</p>
                </div>
                <div class="image-box">
                    <div class="border-box"></div>
                    <div class="img-container">
                        <img src="{{about.image.url}}" alt="About" />
                    </div>
                </div>
            </div>
            {% else %}
            <div class="items">
                <div class="image-box">
                    <div class="border-box"></div>
                    <div class="img-container">
                        <img src="{{about.image.url}}" alt="About" />
                    </div>
                </div>
                <div class="text-box right">
                    <h4>{{about.title}}</h4>
                    <p>{{about.description}}</p>
                </div>
            </div>
            {% endif %}
            {% endfor %}
        </div>
    </div>
</section>
  <!-- testimonials -->
<section id="testimonials">
    <div class="wrapper">
        <div class="head">
        <h2>Testimonials</h2>
        </div>
        <div class="container">
        <ul class="testimonial-slider">
            {% for t in testimonial %}
            <li>
                <div class="avatar">
                    <h2><img src="{{t.image.url}}" alt="User" /></h2>
                    <div class="name-box">
                    <h3>{{t.name}}</h3>
                    <!-- star-png -->
                    <!-- <span><img src="" alt=""></span> -->
                    </div>
                </div>
                <p>
                    {{t.description}}
                </p>
            </li>
            {% endfor %}
        </ul>
        </div>
    </div>
</section>
  <!-- tedstimonial-end -->

  <!-- pre-loader -->
  <section id="loader">
    <div class="content">
      <div class="right"><span></span></div>
    </div>
  </section>


{% endblock%}

templates/web/web_base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Abdul Rasool - Home</title>
    {% load static %}
    <meta name="description" content="" />
    <meta property="og:description" content="" />
    <meta property="og:title" content="" />
    <meta property="og:image" content="{% static 'web/images/logo.png'%}" />
    <!-- links -->

    <link rel="stylesheet" href="{% static 'web/css/style.css'%}" />
    <link rel="stylesheet" href="{% static 'web/css/all.css'%}" />
    <link rel="stylesheet" href="{% static 'web/css/animate.css'%}" />
    <link rel="stylesheet" href="{% static 'web/css/slick-theme.css'%}" />
    <link rel="stylesheet" href="{% static 'web/css/slick.css'%}" />

    <!-- scripts -->
    <script src="{% static 'web/js/jquery-min.js'%}"></script>
    <script src="{% static 'web/js/slick.min.js'%}"></script>
    <!-- <script src="{% static 'web/js/paging.js'%}"></script> -->
    <script src="{% static 'web/js/script.js'%}" defer></script>
    <script src="{% static 'web/js/ajax.js'%}" defer></script>

    <!-- favicon -->
    <link rel="icon" href="{% static 'web/images/logo.png'%}" />
  </head>
  <body onload="product_onload_ajax()">
    <section id="home">
      <header>
        <div class="wrapper">
          <div class="logo">
            <a href="index.html"><img src="{% static 'web/images/logo.png'%}" height="60" alt="Logo" /></a>
          </div>
          <nav>
            <ul>
              <li class="active"><a href="#">home</a></li>
              <li><a href="#services">services</a></li>
              <li><a href="#">products</a></li>
              <li><a href="#careers">careers</a></li>
              <li><a href="#about">about us</a></li>
              <li><a href="#contact">contact us</a></li>
            </ul>
          </nav>
        </div>
      </header>
      <main>
      <div class="wrapper">
          <div class="container">
            <div class="text-box">
              <h3>Choose the best Furnitures for your home!</h3>
              <p>Buy Furniture Online at Abdul Rasool
                Unlimited Choices. Unbeatable Prices. 
                Create beautiful spaces with thoughtful, elegant furniture from Durian for your home and office.</p>
              <!-- this button may use in fututre -->
              <!-- <button>
                <a href="#" class="button">
                  <span><i class="fa-solid fa-play"></i></span>
                  <small>Play Video</small>
                </a>
              </button> -->
            </div>
          </div>
          <div class="bottom-box">
            <a href="#provide"><i class="fa-solid fa-arrow-down-long"></i></a>
          </div>
        </div>
      </main>
    </section>
    <!-- spotlight-end -->
    {% block content %}


    {% endblock content %}
    <footer>
        <div class="wrapper">
          <div class="logo-box">
            <h1>
              <a href="index.html"><img src="{% static 'web/images/logo.png'%}" height="60" alt="Logo" /></a>
            </h1>
            <h2>Abdul-Rasool-Co</h2>
            <ul>
              <li>
                <a target="_blank" href="{{connect.instagram_link}}">
                  <img src="{% static 'web/images/Vector.svg'%}" alt="Instagram" /></a>
              </li>
              <li>
                <a target="_blank" href="{{connect.facebook_link}}"
                  ><img src="{% static 'web/images/Vector-1.svg'%}" alt="Instagram"
                /></a>
              </li>
              <li>
                <a target="_blank" href="{{connect.twitter_link}}"
                  ><img src="{% static 'web/images/Vector-2.svg'%}" alt="Instagram"
                /></a>
              </li>
              <li>
                <a target="_blank" href="{{connect.linkedin_link}}"
                  ><img src="{% static 'web/images/Vector-3.svg'%}" alt="Instagram"
                /></a>
              </li>
            </ul>
          </div>
          <div id="contact" class="content-box">
            <div class="item">
              <h6>Terms & Policy</h6>
              <ul>
                <li><a href="#home">Home</a></li>
                <li><a href="#services">Services</a></li>
                <li><a href="javascript:void(0)">Products</a></li>
                <li><a href="#careers">Careers</a></li>
                <li><a href="#about">About Us</a></li>
                <li><a href="#contact">Contact Us</a></li>
              </ul>
            </div>
            <div class="item main">
              <h6>Main Office</h6>
              <ul>
                <li>
                  <a href=""
                    ><div class="icon"><i class="fa-solid fa-phone"></i></div>
                    <span>{{main_address.phone}}</span></a
                  >
                </li>
                <li>
                  <a href=""
                    ><div class="icon"><i class="fa-solid fa-envelope"></i></div>
                    <span>{{main_address.email}}</span></a
                  >
                </li>
                <li>
                  <a target="_blank" href="{{main_address.location_url}}"
                    ><div class="icon">
                      <i class="fa-solid fa-location-dot"></i>
                    </div>
                    <span
                      >{{main_address.location}}</span
                    ></a
                  >
                </li>
              </ul>
            </div>
            <div class="item main">
              <h6>Sub Office</h6>
              <ul>
                <li>
                  <a href=""
                    ><div class="icon"><i class="fa-solid fa-phone"></i></div>
                    <span>{{sub_address.phone}}</span></a
                  >
                </li>
                <li>
                  <a href=""
                    ><div class="icon"><i class="fa-solid fa-envelope"></i></div>
                    <span>{{sub_address.email}}</span></a
                  >
                </li>
                <li>
                  <a target="_blank" href="{{sub_address.location_url}}"
                    ><div class="icon">
                      <i class="fa-solid fa-location-dot"></i>
                    </div>
                    <span
                      >{{sub_address.location}}</span
                    ></a
                  >
                </li>
              </ul>
            </div>
          </div>
        </div>
        <div class="copyright">
          <p>
            &copy; All rights reserved | Designed and developed by
            <a href="https://tegain.com/" target="_blank">Tegain</a>
          </p>
        </div>
      </footer>

      <!-- <script>
        $('#listitems').paging({limit:6});
    </script> -->

    </body>
  </html>