abdulrasool/urls.py
from django.contrib import admin
from django.views.static import serve
from django.urls import include, path, re_path
from abdulrasool import settings
from main import views as general_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app/accounts/', include('registration.backends.default.urls')),
    path('super-admin/',include(('main.urls'),namespace='main')),
    path('super-admin/',general_views.app,name='app'),
    
    # admin panel
    path('super-admin/product/',include(('product.urls'),namespace='product')),
    path('super-admin/web/',include(('web.urls'),namespace='web')),
    
    # web
    path('', include('web.urls', namespace="web")),    
    
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT})
]

product/urls.py
from . import views
from django.urls import path, re_path

# Create your tests here.

app_name = 'product'

urlpatterns = [
    path('category/', views.category_view, name='category'),
    re_path(r'^category-view/(?P<pk>.*)/$', views.category_single_view, name='category_single'),
    re_path(r'^create-category/$', views.create_category_view, name='create_category'),
    re_path(r'^edit-category/(?P<pk>.*)/$', views.edit_category_view, name='edit_category'),
    re_path(r'^delete-category/(?P<pk>.*)/$', views.delete_category_view, name='delete_category'),


    path('product/', views.product_view, name='product'),
    re_path(r'^product-view/(?P<pk>.*)/$', views.product_single_view, name='product_single'),
    re_path(r'^create-product/$', views.create_product_view, name='create_product'),
    re_path(r'^edit-product/(?P<pk>.*)/$', views.edit_product_view, name='edit_product'),
    re_path(r'^delete-product/(?P<pk>.*)/$', views.delete_product_view, name='delete_product'),
]

web/urls.py
from . import views
from django.urls import path, re_path

# Create your tests here.

app_name = 'web'

urlpatterns = [
    path('', views.index, name="index"),
    path('product-category', views.product_category_view, name="product_category"),
    
    path('service/', views.service_view, name='service'),
    re_path(r'^service-view/(?P<pk>.*)/$', views.service_single_view, name='service_single'),
    re_path(r'^create-service/$', views.create_service_view, name='create_service'),
    re_path(r'^edit-service/(?P<pk>.*)/$', views.edit_service_view, name='edit_service'),
    re_path(r'^delete-service/(?P<pk>.*)/$', views.delete_service_view, name='delete_service'),
    
    
    path('career/', views.career_view, name='career'),
    re_path(r'^career-view/(?P<pk>.*)/$', views.career_single_view, name='career_single'),
    re_path(r'^create-career/$', views.create_career_view, name='create_career'),
    re_path(r'^edit-career/(?P<pk>.*)/$', views.edit_career_view, name='edit_career'),
    re_path(r'^delete-career/(?P<pk>.*)/$', views.delete_career_view, name='delete_career'),
    
    
    path('team-member/', views.team_members_view, name='team_member'),
    re_path(r'^team-member-view/(?P<pk>.*)/$', views.team_members_single_view, name='team_single'),
    re_path(r'^create-team-member/$', views.create_team_member_view, name='create_team_member'),
    re_path(r'^edit-team-member/(?P<pk>.*)/$', views.edit_team_member_view, name='edit_team_member'),
    re_path(r'^delete-team-member/(?P<pk>.*)/$', views.delete_team_member_view, name='delete_team_member'),
    
    
    path('about-us/', views.about_us_view, name='about_us'),
    re_path(r'^about-us-view/(?P<pk>.*)/$', views.about_us_single_view, name='about_us_single'),
    re_path(r'^create-about-us/$', views.create_about_us_view, name='create_about_us'),
    re_path(r'^edit-about-us/(?P<pk>.*)/$', views.edit_about_us_view, name='edit_about_us'),
    re_path(r'^delete-about-us/(?P<pk>.*)/$', views.delete_about_us_view, name='delete_about_us'),


    path('testimonial/', views.testimonial_view, name='testimonial'),
    re_path(r'^testimonial-view/(?P<pk>.*)/$', views.testimonial_single_view, name='testimonial_single'),
    re_path(r'^create-testimonial/$', views.create_testimonial_view, name='create_testimonial'),
    re_path(r'^edit-testimonial/(?P<pk>.*)/$', views.edit_testimonial_view, name='edit_testimonial'),
    re_path(r'^delete-testimonial/(?P<pk>.*)/$', views.delete_testimonial_view, name='delete_testimonial'),
    
    
    path('address/', views.address_view, name='address'),
    re_path(r'^address-view/(?P<pk>.*)/$', views.address_single_view, name='address_single'),
    re_path(r'^create-address/$', views.create_address_view, name='create_address'),
    re_path(r'^edit-address/(?P<pk>.*)/$', views.edit_address_view, name='edit_address'),
    re_path(r'^delete-address/(?P<pk>.*)/$', views.delete_address_view, name='delete_address'),
    
    
    path('connect/', views.connect_view, name='connect'),
    re_path(r'^create-connect/$', views.create_connect_view, name='create_connect'),
    re_path(r'^edit-connect/(?P<pk>.*)/$', views.edit_connect_view, name='edit_connect'),
    re_path(r'^delete-connect/(?P<pk>.*)/$', views.delete_connect_view, name='delete_connect'),
    
    path('description/', views.description_view, name='description'),
    re_path(r'^create-description/$', views.create_description_view, name='create_description'),
    re_path(r'^edit-description/(?P<pk>.*)/$', views.edit_description_view, name='edit_description'),

]

templates/admin_panel/includes/sidebar/super_admin_side_bar.html
{% load static %}
<div class="left-sidenav">
    <!-- LOGO -->
    <div class="brand">
        <a href="{% url 'app' %}" class="logo">
            <span>
                <img src="{% static 'admin_panel/assets/images/logo/AR_logo.jpeg' %}" alt="logo-small" class="logo-sm" style="height: 50px;">
            </span>
            {% comment %} <span>
                <img src="{% static 'admin_panel/assets/images/Abdulrasool-logo/Abdulrasool Logo 2.svg' %}" alt="logo-large" class="logo-lg logo-light">
                <img src="{% static 'admin_panel/assets/images/Abdulrasool-logo/Abdulrasool Logo 2.svg' %}" alt="logo-large" class="logo-lg logo-dark">
            </span> {% endcomment %}
        </a>
    </div>
    <!--end logo-->
    <div class="menu-content h-100" data-simplebar>
        <ul class="metismenu left-sidenav-menu">
            <li class="menu-label mt-0">Main</li>
            <li>
                <a href="{% url 'app' %}"> <i data-feather="home" class="align-self-center menu-icon"></i><span>Dashboard</span><span class="menu-arrow"><i class="mdi mdi-chevron-down"></i></span></a>
            </li>
            
            <li class="nav-item d-flex justify-content-between">
                <a class="nav-link" href="{% url 'product:category' %}"><i class="ti-control-record"></i>Categories</a>
                <a class="nav-link" href="{% url 'product:create_category' %}"><i class="ti-plus"></i></a>
            </li>

            <li class="nav-item d-flex justify-content-between">
                <a class="nav-link" href="{% url 'product:product' %}"><i class="ti-control-record"></i>Products</a>
                <a class="nav-link" href="{% url 'product:create_product' %}"><i class="ti-plus"></i></a>
            </li>

            <li class="nav-item d-flex justify-content-between">
                <a class="nav-link" href="{% url 'web:service' %}"><i class="ti-control-record"></i>Services</a>
                <a class="nav-link" href="{% url 'web:create_service' %}"><i class="ti-plus"></i></a>
            </li>

            <li class="nav-item d-flex justify-content-between">
                <a class="nav-link" href="{% url 'web:career' %}"><i class="ti-control-record"></i>Careers</a>
                <a class="nav-link" href="{% url 'web:create_career' %}"><i class="ti-plus"></i></a>
            </li>

            <li class="nav-item d-flex justify-content-between">
                <a class="nav-link" href="{% url 'web:team_member' %}"><i class="ti-control-record"></i>Team Member</a>
                <a class="nav-link" href="{% url 'web:create_team_member' %}"><i class="ti-plus"></i></a>
            </li>

            <li class="nav-item d-flex justify-content-between">
                <a class="nav-link" href="{% url 'web:testimonial' %}"><i class="ti-control-record"></i>Testimonial</a>
                <a class="nav-link" href="{% url 'web:create_testimonial' %}"><i class="ti-plus"></i></a>
            </li>

            <li class="nav-item d-flex justify-content-between">
                <a class="nav-link" href="{% url 'web:address' %}"><i class="ti-control-record"></i>Address</a>
                <a class="nav-link" href="{% url 'web:create_address' %}"><i class="ti-plus"></i></a>
            </li>

            <li class="nav-item d-flex justify-content-between">
                <a class="nav-link" href="{% url 'web:connect' %}"><i class="ti-control-record"></i>Connect</a>
                <a class="nav-link" href="{% url 'web:create_connect' %}"><i class="ti-plus"></i></a>
            </li>
            
            <li class="nav-item d-flex justify-content-between">
                <a class="nav-link" href="{% url 'web:description' %}"><i class="ti-control-record"></i>Descriptions</a>
                {% if is_description <= 0 %}
                <a class="nav-link" href="{% url 'web:create_description' %}"><i class="ti-plus"></i></a>
                {% endif %}
            </li>
            
            <li class="nav-item d-flex justify-content-between">
                <a class="nav-link" href="{% url 'web:about_us' %}"><i class="ti-control-record"></i>About Us</a>
                <a class="nav-link" href="{% url 'web:create_about_us' %}"><i class="ti-plus"></i></a>
            </li>

        </ul>
    </div>
</div>